config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'reddit/index'

  get 'posts/index'

  root 'reddit#index'

  resources :posts do
    get :autocomplete_subreddit_title, :on => :collection
  end

  resources :comments
  resources :posts
  resources :subreddits
  resources :subscribers

  resources :post_votes

  resources :comment_votes

  resources :posts do
    resources :comments
  end

  resources :users do
    resources :posts
  end

  resources :users do
    resources :subscribers
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/profile' => 'users#show'

  get '/subscribers' => 'subscribers#create'

end

app/controllers/reddit_controller.rb
class RedditController < ApplicationController
  def index
  	session.delete(:subreddit_id)


		subscribed_subreddit_ids = Subscriber.where(user_id: session[:user_id]).map {|subscriber| subscriber.subreddit_id}
		@posts = subscribed_subreddit_ids.map { |s| Post.where(subreddit_id: s)}.flatten
		@posts += Post.all - @posts
		  	if params[:sort]
		  		p "Params Sort : "+params[:sort]
		  		if params[:direction] == 'asc'
					@posts.sort_by!(&params[:sort].to_sym)
      		elsif params[:direction] == 'desc'
      		@posts.sort_by!(&params[:sort].to_sym).reverse!
      	end
			end
		@posts = @posts.paginate(page: params[:page], per_page: 5)
		@vote_count_arr = @posts.map { |p| PostVote.where(post_id: p.id).inject(0) {|sum,pv| sum+pv.vote_val}}
		@post_subreddit = @posts.map { |p| Subreddit.find(p.subreddit_id)}
		
  end
end

app/helpers/reddit_helper.rb
module RedditHelper
end

app/views/reddit/_posts_body.html.erb
<div class="col-sm-8 col-sm-pull-4">
<div class="sort-links">
Sort By: 
<%= sortable "title" %>
<%= sortable "created_at", "Date" %>
</div>
	<% @posts.each_with_index do |post,index| %>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div id="<%=post.id%>" class="tar col-md-2 col-sm-4 col-xs-4 text-center">
						<p class="vote_value">
							<%=@vote_count_arr[index] %>
						</p>

						<% if session[:user_id] %>
							<p>
								<%= link_to(raw("<span class='glyphicon glyphicon-arrow-up icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_up '+ vote_state(find_post_vote_val(post.id, current_user.id))["up"])%> <%= link_to(raw("<span class='glyphicon glyphicon-arrow-down icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_down '+vote_state(find_post_vote_val(post.id, current_user.id))["down"])%>
							</p>
						<% end %>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-2">
						<% if post.link %>
							<% if post.link =~ /^https?:\/\/(?:[a-z\-]+\.)+[a-z]{2,6}(?:\/[^\/#?]+)+\.(?:jpg|gif|png)$/ %>
								<%= image_tag post.link, size:"90x90", class: "thumb-image" %>
							<% else %>
								<%= image_tag get_image(post.link), size: "90x90", class: "thumb-image" %>
							<% end %>
						<% elsif post.content %>
							<%= image_tag "http://placehold.it/90x90", size: "90x90", class: "thumb-image" %>
						<% end %>
					</div>
					<div class="col-md-8 col-sm-6 col-xs-6">
						<h3>
							<% if post.content  %>
							<%= link_to post.title, post_path(post) %>
							<% elsif post.link  %>
							<%= link_to post.title, post.link %>
							<span class="span-small-text"><%=link_to "View comments >", post_path(post, :more_params => "link") %></span>
							<% end %>
						</h3><span class="grey_text"><em>Submitted at</em> <%= time_ago_in_words(post.created_at)%> <em>by</em> <%=post.user.name%> <em>to</em> <%=link_to(@post_subreddit[index].title,subreddit_path(@post_subreddit[index]))%></span>
					</div>
				</div>
			</div>
		</div>
	<% end  %>
	<div class="row text-center"> 
		<%= will_paginate @posts  %>				
	</div>
</div>

app/views/reddit/_search_form.html.erb
<%= form_tag(posts_path, :method => "get", id: "search-form", class: "form-inline") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Posts",class: "form-control input-small search_field"  %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>

<% end %>

app/views/reddit/_sidebar.html.erb
<div class="col-sm-4 col-sm-push-8 sidebar">
	<div class="row">
		<div class="col-md-12">
			<div class = "row" style="padding-bottom: 20px">
				<%= render 'search_form'  %>
			</div>
			<div class="row" style="padding-bottom: 20px">
				<%= link_to 'Submit a new text post', new_user_post_path(current_user),:class => 'btn btn-default'  if current_user  %>
			</div>
			<div class="row">
				<%= link_to 'Submit a link', new_user_post_path(current_user, :more_params => "link"),:class => 'btn btn-default'  if current_user  %>
			</div>
			<div class="row">
				<%= render 'subreddit_create'  if current_user%>
			</div>
			<div class="row">
				<%= render 'subreddit_dropdown'  if current_user%>
			</div>
		</div>
	</div>
	
</div>

app/views/reddit/_subreddit_create.html.erb
<form class="form-inline" action="/subreddits" accept-charset="UTF-8" data-remote="true" method="post">
	<div class="form-group">
		<input class="input-small" name="utf8" type="hidden" value="✓">
	</div>
	<div class="form-group sr-title">
		<input class="form-control input-small subreddit_title_field" placeholder="Create new subreddit" type="text" name="subreddit[title]" id="subreddit_title">
	</div> <button type="submit" name="commit" class="btn btn-default new-subreddit">Submit</button>
</form>

app/views/reddit/_subreddit_dropdown.html.erb
<div class="row" style="padding-top: 20px">
	<div class="col-md-12">
		<div class="dropdown">
			<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">My Subreddits</button>
			<ul class="dropdown-menu" role="menu">
				<% current_user.subreddits.each do |subreddit| %>
				<li role="presentation">
					<%=link_to subreddit.title, subreddit_path(subreddit)  %>
				</li><% end %>
			</ul>
		</div>
	</div>
</div>

app/views/reddit/index.html.erb
<html>
	<head>
		<title></title>
	</head>
	<body>

		<div class="row">
			<%= render 'sidebar' %>
			<%= render 'posts_body'  %>	

		</div>
	</body>
</html>