config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'reddit/index'

  get 'posts/index'

  root 'reddit#index'

  resources :posts do
    get :autocomplete_subreddit_title, :on => :collection
  end

  resources :comments
  resources :posts
  resources :subreddits
  resources :subscribers

  resources :post_votes

  resources :comment_votes

  resources :posts do
    resources :comments
  end

  resources :users do
    resources :posts
  end

  resources :users do
    resources :subscribers
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/profile' => 'users#show'

  get '/subscribers' => 'subscribers#create'

end

app/models/post.rb
class Post < ActiveRecord::Base
  profanity_filter :title, :content, :method => 'hollow'
  validates :title, length: {minimum: 25, maximum: 300}
  validates :content, allow_blank: true, length: { minimum: 100, maximum: 40000}
  validates :link, allow_blank: true, format: {with: URI.regexp}
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :subreddit
  
  def self.search(query)
  	where("lower(title) like ? OR lower(content) like ? OR lower(link) like ?", "%#{query.downcase}%","%#{query.downcase}%","%#{query.downcase}%") 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  autocomplete :subreddit, :title
  before_filter :authorize
  
  def index
    
    if params[:search]
      @search = true
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @search = false
      @posts = Post.all.order('created_at DESC')
    end
    @vote_count_arr = @posts.map { |p| PostVote.where(post_id: p.id).inject(0) {|sum,pv| sum+pv.vote_val}}
    @post_subreddit = @posts.map { |p| Subreddit.find(p.subreddit_id)}
  end

  def new
    @link_flag = true if params[:more_params] == "link"
    @subreddit_name = Subreddit.find(session[:subreddit_id]).title if session[:subreddit_id]
  end

  def create
  	@post = Post.new(title: post_params["title"], content: post_params["content"]) if post_params["content"]
    @post = Post.new(title: post_params["title"], link: post_params["link"]) if post_params["link"]
    @subreddit = Subreddit.find_by(title: post_params[:subreddit_title])
    if @subreddit
      @post.subreddit_id = @subreddit.id
    	@post.user_id = current_user.id
    	if @post.save
    		redirect_to '/'
    	else
        flash[:error] = "Title must have at least 25 characters and content must have at least 100 characters"
    		redirect_to new_user_post_path(current_user, :more_params => "link")
    	end
    else
      flash[:error] = "Subreddit does not exist!"
      redirect_to new_user_post_path(current_user, :more_params => "link")
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.content = post_params["content"] if post_params["content"]
    @post.link = post_params["link"] if post_params["link"]
    if @post.save
      redirect_to post_path
    else
      flash[:error] = "Content must have at least 100 characters" if post_params["content"]
      flash[:error] = "Link not valid" if post_params["content"]
      redirect_to new_user_post_path(current_user)
    end
  end
  def show
    @vote_count_post = PostVote.where(post_id: params[:id]).sum(:vote_val)
    cids = Comment.all.map { |c| c.id}
    @vote_count_arr = cids.map { |cid| CommentVote.where(comment_id: cid).inject(0) {|sum,cv| sum+cv.vote_val}}
  	@post = Post.find(params[:id])
  	@comment = Comment.where(post_id: params[:id])
    @vote_val = PostVote.where(user_id: session[:user_id], post_id: @post.id).first.vote_val if PostVote.exists?(user_id: session[:user_id], post_id: @post.id)  
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to '/'
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :subreddit_title, :more_params, :link)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/views/posts/_comments_body.html.erb
<div class="col-md-12">
	<h3>
		Add a comment
	</h3>	
	<%= form_for :comments, url: post_comments_path(@post), :class => 'form-group' do |f| %>

		<%= f.text_area :content, size: "2x2", :class => 'form-control' %><br>
		<%= f.submit 'Comment', :class => 'btn btn-default'  %> <br>

	<% end%>
	<% @vote_count_arr.reverse! %> <% @post.comments.reverse.each_with_index do |comment,index| %>
		<div class="well rm-pad">
			<div class="row">
				<div id="<%=comment.id%>" class="tar col-md-2 col-sm-4 col-xs-4 text-center">
					<p class="vote_value">
						<%=@vote_count_arr[index] %>
					</p>
					<% if current_user %>
					<p>
						<%= link_to(raw("<span class='glyphicon glyphicon-arrow-up icon_comment'></span>"),comment_votes_path, :remote => true, :class => 'comment_vote_up '+vote_state(find_comment_vote_val(comment.id, current_user.id))["up"])%> <%= link_to(raw("<span class='glyphicon glyphicon-arrow-down icon_comment'></span>"),comment_votes_path, :remote => true, :class => 'comment_vote_down '+vote_state(find_comment_vote_val(comment.id, current_user.id))["down"])%>
					</p>
					<% end %>
				</div>
				<div class="col-md-10 col-sm-6 col-xs-8">
					<h4>
						<%=comment.user.name  %> <em>said</em>: <%=  comment.content %>
					</h4><span style=""><em><%= time_ago_in_words(comment.created_at)%> ago</em></span><br>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/posts/_new_link_form.html.erb
<h1>Add a new link</h1>
<%=form_for :post, url: user_posts_path(current_user), class: 'form-group' do |f| %>
	<%=f.label :title %>
	<%=f.text_field :title, class: 'form-control title_field' %><span id="characterLeftTitle" style="float: right;"></span><br>

	<%=f.label :link  %>
	<%=f.url_field :link, class: 'form-control content_field' %><br>

	<%=f.label :subreddit  %>
	<%=f.autocomplete_field :subreddit_title, autocomplete_subreddit_title_posts_path, class: 'form-control subreddit_field'%><br>

	<%=f.submit 'Post', :class => 'btn btn-default new-post'  %>
<% end %>

app/views/posts/_new_post_form.html.erb
<h1>Add a new post</h1>
<%=form_for :post, url: user_posts_path(current_user), class: 'form-group' do |f| %>
	<%=f.label :title %>
	<%=f.text_field :title, class: 'form-control title_field' %><span id="characterLeftTitle" style="float: right;"></span><br>

	<%=f.label :content  %>
	<%=f.text_area :content, class: 'form-control content_field' %><span id="characterLeftContent" style="float: right;"></span><br>

	<%=f.label :subreddit  %>
	<%=f.autocomplete_field :subreddit_title, autocomplete_subreddit_title_posts_path, class: 'form-control subreddit_field'%><br>

	<%=f.submit 'Post', :class => 'btn btn-default new-post'  %>
<% end %>

app/views/posts/_post_body.html.erb
    <div id="<%=@post.id%>" class="tar col-md-2 col-sm-2 col-xs-2 text-center" >

			<p class="vote_value"> <%=@vote_count_post %><p>
			<% if current_user %>
				<p>
					<%= link_to(raw("<span class='glyphicon glyphicon-arrow-up icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_up '+vote_state(@vote_val)["up"])%>
					<%= link_to(raw("<span class='glyphicon glyphicon-arrow-down icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_down '+vote_state(@vote_val)["down"])%>
				</p>
			<% end %>
		</div>
	<div class="col-md-2 col-sm-2 col-xs-2">
		<% if @post.link %>
			<% if @post.link =~ /^https?:\/\/(?:[a-z\-]+\.)+[a-z]{2,6}(?:\/[^\/#?]+)+\.(?:jpg|gif|png)$/ %>
				<%= image_tag @post.link, size:"90x90"%>
			<% else %>
				<%= image_tag get_image(@post.link), size: "90x90" %>
			<% end %>
		<% elsif @post.content %>
			<%= image_tag "http://placehold.it/90x90", size: "90x90" %>
		<% end %>
	</div>
	<div class="col-md-8 col-sm-8 col-xs-8">
		<% if @post.content %>
			<h3><%= @post.title %></h3>
			<p><%=@post.content  %></p>
		<% elsif @post.link  %>
			<h3><%= link_to(@post.title,@post.link) %></h3>
		<% end %>


<% if session[:user_id] == @post.user_id %>

	<%= form_for([@post], class: 'form-group') do |f| %>
		<% if @post.content %>
			<%= f.text_area :content, class: 'form-control' %>
		<% elsif @post.link %>
			<%= f.url_field :link, class: 'form-control' %>
		<% end %>
		<br><br>

		<%= f.submit "Update", class: "btn btn-default" %>
	<% end%>
	<br>
	<%=link_to("Delete", post_path, method: :delete, class: "btn btn-default" ) %>
<% end %>
	</div>

app/views/posts/_posts_body.html.erb
<div class="col-sm-8">
	<% @posts.each_with_index do |post,index| %>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div id="<%=post.id%>" class="tar col-md-2 col-sm-4 col-xs-4 text-center">
						<p class="vote_value">
							<%=@vote_count_arr[index] %>
						</p>

						<% if session[:user_id] %>
							<p>
								<%= link_to(raw("<span class='glyphicon glyphicon-arrow-up icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_up '+ vote_state(find_post_vote_val(post.id, current_user.id))["up"])%> <%= link_to(raw("<span class='glyphicon glyphicon-arrow-down icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_down '+vote_state(find_post_vote_val(post.id, current_user.id))["down"])%>
							</p>
						<% end %>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-2">
						<% if post.link %>
							<% if post.link =~ /^https?:\/\/(?:[a-z\-]+\.)+[a-z]{2,6}(?:\/[^\/#?]+)+\.(?:jpg|gif|png)$/ %>
								<%= image_tag post.link, size:"90x90", class: "thumb-image"%>
							<% else %>
								<%= image_tag get_image(post.link), size: "90x90", class: "thumb-image" %>
							<% end %>
						<% elsif post.content %>
							<%= image_tag "http://placehold.it/90x90", size: "90x90", class: "thumb-image" %>
						<% end %>
					</div>
					<div class="col-md-8 col-sm-6 col-xs-6">
						<h3>
							<% if post.content  %>
							<%= link_to post.title, post_path(post) %>
							<% elsif post.link  %>
							<%= link_to post.title, post.link %>
							<span class="span-small-text"><%=link_to "View comments >", post_path(post, :more_params => "link") %></span>
							<% end %>
						</h3><span class="grey_text"><em>Submitted at</em> <%= time_ago_in_words(post.created_at)%> <em>by</em> <%=post.user.name%> <em>to</em> <%=link_to(@post_subreddit[index].title,subreddit_path(@post_subreddit[index]))%></span>
					</div>
				</div>
			</div>
		</div>
	<% end  %>
</div>

app/views/posts/index.html.erb
	<% if @search == true %>
	<h3>Your Search Results</h3>
	<br>
	<% p @post %>
	<% if @post == nil %>
	<br>
	<h2>Sorry Nothing Found !!</h2>
	<% end %>
	<% end %>
<div class="row">

	<%= render 'posts_body'  %>	
</div>

app/views/posts/new.html.erb
<div class="form-outer">
	<% if @link_flag%>
		<%= render 'new_link_form' %>
	<% else %>
		<%= render 'new_post_form' %>
	<% end %>
<br>
<p>
	<em>You Have Subscribed to</em><br>
	<% subscriber_list = Subscriber.where(user_id: current_user.id) %>
	<% subscriber_list.each do |item| %>
	<%= link_to(Subreddit.find(item.subreddit_id).title, subreddit_path(Subreddit.find(item.subreddit.id))) %>

<% end%>

</p>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<%= render 'post_body'%>	
	</div>
	<div class="row">
		<%= render 'comments_body'%>
	</div>
</div>
	