config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'reddit/index'

  get 'posts/index'

  root 'reddit#index'

  resources :posts do
    get :autocomplete_subreddit_title, :on => :collection
  end

  resources :comments
  resources :posts
  resources :subreddits
  resources :subscribers

  resources :post_votes

  resources :comment_votes

  resources :posts do
    resources :comments
  end

  resources :users do
    resources :posts
  end

  resources :users do
    resources :subscribers
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/profile' => 'users#show'

  get '/subscribers' => 'subscribers#create'

end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
	profanity_filter :title, :method => 'hollow'
	validates :title, uniqueness: true, length: {minimum: 3, maximum:20}
	validates_format_of :title, :with => /\A(^[A-Za-z0-9]+$)\z/
	has_many :posts, dependent: :destroy
	has_many :subscribers, dependent: :destroy
	has_many :users, through: :subscribers
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  def index
    @subreddits = Subreddit.all
  end
  def new
  end
  def create
    @subreddit = Subreddit.new(title: params[:subreddit_title].downcase)
    respond_to do |format|
      if @subreddit.save
        format.js { render 'create.js.erb' }
      else
      	@error = @subreddit.errors.full_messages.to_sentence
        format.js { render 'error.js.erb' }
      end
    end
  end
  def show
    @subreddit = Subreddit.find(params[:id])
    session[:subreddit_id] = params[:id]
    @subscriber_count = Subscriber.where(subreddit_id: params[:id]).count
    pids = Post.where(subreddit_id: params[:id]).map { |p| p.id}
    @vote_count_arr = pids.map { |pid| PostVote.where(post_id: pid).inject(0) {|sum,pv| sum+pv.vote_val}}
    @posts = Post.where(subreddit_id: params[:id])
  end

end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/views/subreddits/_post_body.html.erb
<div class="col-md-10 col-sm-10 col-xs-12">
	<% @posts.each_with_index do |post,index| %>
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="row">
				<div id="<%=post.id%>" class="tar col-md-2 col-sm-2 col-xs-2 text-center">
					<p class="vote_value">
						<%=@vote_count_arr[index] %>
					</p><% if session[:user_id] %>
					<p>
						<%= link_to(raw("<span class='glyphicon glyphicon-arrow-up icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_up '+vote_state(find_post_vote_val(post.id, current_user.id))["up"])%> <%= link_to(raw("<span class='glyphicon glyphicon-arrow-down icon'></span>"),post_votes_path, :remote => true, :class => 'post_vote_down '+vote_state(find_post_vote_val(post.id, current_user.id))["down"])%>
					</p><% end %>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-2">
					<% if post.link %>
						<% if post.link =~ /^https?:\/\/(?:[a-z\-]+\.)+[a-z]{2,6}(?:\/[^\/#?]+)+\.(?:jpg|gif|png)$/ %>
							<%= image_tag post.link, size:"90x90"%>
						<% else %>
							<%= image_tag get_image(post.link), size: "90x90" %>
						<% end %>
					<% elsif post.content %>
						<%= image_tag "http://placehold.it/90x90", size: "90x90" %>
					<% end %>
				</div>
				<div class="col-md-8 col-sm-8 col-xs-8">
					<h3>
						<% if post.content  %> <%= link_to post.title, post_path(post) %> <% elsif post.link  %> <%= link_to post.title, post.link %> <em><%=link_to "view comments", post_path(post, :more_params => "link") %></em> <% end %>
					</h3><span class="grey_text"><em>Submitted at</em> <%= time_ago_in_words(post.created_at)%> <em>by</em> <%=post.user.name%></span>
				</div>
			</div><!-- row end -->
		</div><!-- panel body end -->
	</div><!-- panel end -->
	<% end  %>
</div><!-- col ends -->

app/views/subreddits/_sidebar.html.erb
<div class="col-md-2 col-sm-2 col-xs-12 text-center">
	<%= link_to 'New Post', new_user_post_path(current_user), :class => 'btn btn-default btn-full'  if current_user  %><% if Subscriber.exists?(user_id: session[:user_id], subreddit_id: @subreddit.id) %><% sub_check = '' %><% link_val = 'Unsubscribe' %><% else %><% link_val = 'Subscribe' %><% sub_check = 'in-active' %><% end %>
	<div id="<%= @subreddit.id %>">
		<br>
		<span>subscribers</span> <span class="subscriber_count badge"><%=@subscriber_count%></span><br>
		<br>
		<%= link_to(link_val, subscribers_path,:remote => true, :class => 'btn btn-sm btn-default subscribed '+sub_check ) if current_user%>
	</div>
</div><!-- col ends -->

app/views/subreddits/create.js.erb
$('.sidebar').append('<div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> Success! <%=link_to @subreddit.title,subreddit_path(@subreddit) %> created! </div>');
$('.title_field').append('<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>');
$('.sr-title').addClass('has-success');

app/views/subreddits/error.js.erb
$('.sidebar').append('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <%= @error %></div>');
$('.sr-title').addClass('has-error');

app/views/subreddits/index.html.erb
<h2> Subreddits </h2>

<% @subreddits.each do |subreddit| %>
	<%= link_to(subreddit.title,subreddit_path(subreddit)) %> <br>
<% end %>

app/views/subreddits/show.html.erb
<html>
	<head>
		<title></title>
	</head>
	<body>
		<h1>
			<%=@subreddit.title.capitalize%> Posts
		</h1>
		<div class="row">
			<%= render 'post_body'  %>
			<%= render 'sidebar' %>
		</div><!-- row ends -->
	</body>
</html>